"""Branching v6 — candidate-strategy zoo + sampled-prefix feasibility.

Strategies for constructing candidate next-windows at a branch state
(shifted region = window positions [n_acc, K) of the previous forward;
`stable[j]` = argmax agreed with the input draft at that position — the
"model already knows this token" mask, computable at decode time):

  full      : sample every position from softmax(logits/T)        [v4 baseline]
  keepm     : stable -> argmax, unstable -> sample                [user's idea]
  t05       : sample every position at T=0.5
  top2      : sample each position from renormalized top-2
  prefix4   : first 4 positions argmax, rest sampled
  reppen    : DETERMINISTIC argmax with window-repetition penalty —
              if argmax equals one of the 2 previous chosen window tokens,
              take the runner-up logit instead (1 candidate)
  oraclekeep: argmax where argmax == greedy future, else sample   [CEILING
              probe only — uses the reference future, not decode-computable]

--prefix_mode sampled: the committed prefix before Jacobi decoding begins is
generated by AR sampling at T=1.0 with random length in [120, 320] — branch
states then mimic RL-training rollout states (sampled content) instead of
greedy states. Tests whether the advantage signal survives off-greedy
prefixes (training feasibility).
"""
from __future__ import annotations
import argparse, json, random
import torch
import torch.nn.functional as F
from transformers import AutoModelForCausalLM, AutoTokenizer

STOP_IDS = {151645, 151643}
STOCH = ("full", "keepm", "t05", "top2", "prefix4", "oraclekeep")


def parse_args():
    p = argparse.ArgumentParser()
    p.add_argument("--model", required=True)
    p.add_argument("--prompts_jsonl", required=True)
    p.add_argument("--out_jsonl", required=True)
    p.add_argument("--K", type=int, default=32)
    p.add_argument("--max_new", type=int, default=512)
    p.add_argument("--max_iters", type=int, default=512)
    p.add_argument("--n_per_strat", type=int, default=8)
    p.add_argument("--h", type=int, default=6)
    p.add_argument("--branch_every", type=int, default=12)
    p.add_argument("--n_prompts", type=int, default=6)
    p.add_argument("--prefix_mode", choices=["greedy", "sampled"], default="greedy")
    p.add_argument("--strats", default="full,keepm,t05,top2,prefix4,reppen,oraclekeep")
    p.add_argument("--vocab_size", type=int, default=152064)
    p.add_argument("--seed", type=int, default=42)
    return p.parse_args()


@torch.no_grad()
def fwd(model, committed, draft):
    L = len(committed)
    K = len(draft)
    inp = torch.tensor([committed + draft], dtype=torch.long, device=model.device)
    logits = model(input_ids=inp).logits[0, L - 1 : L - 1 + K, :]
    return logits.argmax(dim=-1).cpu().tolist(), logits


def acc_len(cur, draft):
    n = 0
    for a, b in zip(cur, draft):
        if a != b:
            break
        n += 1
    return n


@torch.no_grad()
def roll(model, committed, draft, h, K, fill_seed, vocab, need_tokens=None):
    rng = random.Random(fill_seed)
    committed = list(committed)
    draft = list(draft)
    cum, out = [], []
    tot, it = 0, 0
    lim = h if need_tokens is None else 4 * h
    stopped = False
    while it < lim:
        if need_tokens is not None and tot >= need_tokens:
            break
        if stopped:
            cum.append(tot); it += 1; continue
        cur, _ = fwd(model, committed, draft)
        it += 1
        n_acc = acc_len(cur, draft)
        if n_acc > 0:
            toks = cur[:n_acc]
            for si, t in enumerate(toks):
                if t in STOP_IDS:
                    toks = toks[: si + 1]; stopped = True; break
            committed += toks; out += toks; tot += len(toks)
        cum.append(tot)
        shifted = cur[n_acc:K]
        draft = shifted + [rng.randrange(vocab) for _ in range(n_acc)]
    return cum, out


def make_cand(strat, argmax_sh, logits_sh, stable, future_sh, fill, rng_t):
    """Build one candidate's shifted-region tokens per strategy."""
    ns = len(argmax_sh)
    if strat == "reppen":
        out = []
        top2 = logits_sh.topk(2, dim=-1).indices.cpu().tolist()
        for j in range(ns):
            t = top2[j][0]
            if out[-2:] and t in out[-2:]:
                t = top2[j][1]
            out.append(t)
        return out + fill
    if strat == "t05":
        probs = F.softmax(logits_sh.float() / 0.5, dim=-1)
        return torch.multinomial(probs, 1).squeeze(-1).cpu().tolist() + fill
    if strat == "top2":
        v2, i2 = logits_sh.float().topk(2, dim=-1)
        p2 = F.softmax(v2, dim=-1)
        pick = torch.multinomial(p2, 1).squeeze(-1)
        return i2.gather(-1, pick.unsqueeze(-1)).squeeze(-1).cpu().tolist() + fill
    probs = F.softmax(logits_sh.float(), dim=-1)
    samp = torch.multinomial(probs, 1).squeeze(-1).cpu().tolist()
    if strat == "full":
        return samp + fill
    if strat == "keepm":
        return [argmax_sh[j] if stable[j] else samp[j] for j in range(ns)] + fill
    if strat == "prefix4":
        return [argmax_sh[j] if j < 4 else samp[j] for j in range(ns)] + fill
    if strat == "oraclekeep":
        return [argmax_sh[j] if (j < len(future_sh) and argmax_sh[j] == future_sh[j])
                else samp[j] for j in range(ns)] + fill
    raise ValueError(strat)


@torch.no_grad()
def run_prompt(model, tok, prompt_ids, args, rng, strats):
    K = args.K
    committed = list(prompt_ids)
    if args.prefix_mode == "sampled":
        plen = rng.randrange(120, 320)
        ids = torch.tensor([committed], device=model.device)
        gen = model.generate(ids, max_new_tokens=plen, do_sample=True,
                             temperature=1.0, pad_token_id=151643)
        committed = gen[0].tolist()
        if committed[-1] in STOP_IDS:
            committed = committed[:-1]
    draft = [rng.randrange(args.vocab_size) for _ in range(K)]
    total, n_fwd, n_commits = 0, 0, 0
    records = []
    while total < args.max_new and n_fwd < args.max_iters:
        cur, logits = fwd(model, committed, draft)
        n_fwd += 1
        n_acc = acc_len(cur, draft)
        if n_acc > 0:
            toks = cur[:n_acc]
            hit = False
            for si, t in enumerate(toks):
                if t in STOP_IDS:
                    toks = toks[: si + 1]; hit = True; break
            committed += toks; total += len(toks); n_commits += 1
            if hit or total >= args.max_new:
                break
        shifted = cur[n_acc:K]
        fill = [rng.randrange(args.vocab_size) for _ in range(n_acc)]
        vanilla_next = shifted + fill

        if n_acc > 0 and n_commits % args.branch_every == 0:
            ns = K - n_acc
            stable = [cur[n_acc + j] == draft[n_acc + j] for j in range(ns)]
            logits_sh = logits[n_acc:K]
            fill_seed = rng.randrange(1 << 30)
            _, future = roll(model, committed, vanilla_next, args.h, K,
                             fill_seed, args.vocab_size, need_tokens=K)
            van_cum, _ = roll(model, committed, vanilla_next, args.h, K,
                              fill_seed, args.vocab_size)
            rec = {"pos": total, "n_shift": ns, "stable_frac": sum(stable) / max(1, ns),
                   "van_cum": van_cum, "strat": {}}
            for s in strats:
                n = 1 if s == "reppen" else args.n_per_strat
                cums = []
                for _ in range(n):
                    cnd = make_cand(s, shifted, logits_sh, stable,
                                    future[:ns], fill, rng)
                    c, _ = roll(model, committed, cnd, args.h, K, fill_seed,
                                args.vocab_size)
                    cums.append(c)
                rec["strat"][s] = cums
            records.append(rec)
        draft = vanilla_next
    return {"n_tokens": total, "branches": records}


def main():
    args = parse_args()
    strats = args.strats.split(",")
    tok = AutoTokenizer.from_pretrained(args.model)
    model = AutoModelForCausalLM.from_pretrained(args.model, dtype=torch.bfloat16,
                                                 device_map="cuda:0")
    model.eval()
    prompts = [json.loads(l) for l in open(args.prompts_jsonl)][: args.n_prompts]
    rng = random.Random(args.seed)
    rows = []
    with open(args.out_jsonl, "w") as f:
        for i, p in enumerate(prompts):
            chat = [{"role": "user", "content": p["input"]}]
            text = tok.apply_chat_template(chat, tokenize=False, add_generation_prompt=True)
            pid = tok(text, return_tensors="pt").input_ids[0].tolist()
            r = run_prompt(model, tok, pid, args, rng, strats)
            r["batch_idx"] = i
            rows.append(r)
            f.write(json.dumps(r) + "\n"); f.flush()
            print(f"[branch6] [{i+1}/{len(prompts)}] tok={r['n_tokens']} "
                  f"branch_points={len(r['branches'])}", flush=True)

    import statistics as st
    B = [b for r in rows for b in r["branches"]]
    h = args.h
    print(f"\n[branch6] prefix_mode={args.prefix_mode}  branch points: {len(B)}  "
          f"mean stable_frac={st.mean(b['stable_frac'] for b in B):.2f}")
    van = [b["van_cum"][h-1] / h for b in B]
    print(f"[branch6] vanilla h-TPF = {st.mean(van):.3f}")
    print(f"[branch6] {'strategy':>10s} {'mean':>7s} {'best-of-n':>9s} {'headroom':>9s} {'win%':>5s}")
    for s in strats:
        means, bests, wins = [], [], 0
        for b in B:
            outs = [c[h-1] / h for c in b["strat"][s]]
            means.append(st.mean(outs))
            bb = max([b["van_cum"][h-1] / h] + outs)
            bests.append(bb)
            if max(outs) > b["van_cum"][h-1] / h:
                wins += 1
        print(f"[branch6] {s:>10s} {st.mean(means):7.3f} {st.mean(bests):9.3f} "
              f"{st.mean(bests)-st.mean(van):9.3f} {100*wins/len(B):4.0f}%")


if __name__ == "__main__":
    main()
